config/routes.rb
Rails.application.routes.draw do
  resources :payment_requests, only: [:index] do
    member do
      post :accept
      post :reject
    end
  end

  root to: 'payment_requests#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment_request.rb
class PaymentRequest < ApplicationRecord
  after_update :notify_contractor

  enum state: {
    pending: 0,
    accepted: 1,
    rejected: 2
  }

  def accept
  	update!(state: 'accepted')
  end

  def reject
  	update!(state: 'rejected')
  end

  def notify_contractor
  	::BUNNY_OBJECT.publish({id: id, state: state}.to_json)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payment_requests_controller.rb
class PaymentRequestsController < ApplicationController
  def index
    @payment_requests = PaymentRequest.all
  end

  def accept
    PaymentRequest.find(params[:id]).accept

    redirect_to payment_requests_path
  end

  def reject
    PaymentRequest.find(params[:id]).reject

    redirect_to payment_requests_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManagerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payment_requests/index.html.erb
<ul>
  <% @payment_requests.each do |payment_request| %>
    <li>
      <%= "#{payment_request.id}: #{payment_request.amount} #{payment_request.currency}, state: #{payment_request.state}" %>
      <%= link_to 'Accept', accept_payment_request_path(payment_request), method: :post %>
      <%= link_to 'Reject', reject_payment_request_path(payment_request), method: :post %>
    </li>
  <% end %>
</ul>